# Generated by Django 6.0.1 on 2026-01-30 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('shop_name', models.CharField(default='', max_length=255)),
                ('role', models.IntegerField(choices=[(0, 'SystemAdmin'), (1, 'Owner'), (2, 'Manager'), (3, 'Staff'), (4, 'UnAssignedUser')], default=3)),
                ('password_hash', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('logo_url', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='BDT', max_length=50)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('profit_margin_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_categories', to='shop.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='shop.company')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shop.company'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('last_purchase_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customers', to='shop.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.IntegerField(choices=[(0, 'SystemAdmin'), (1, 'Owner'), (2, 'Manager'), (3, 'Staff'), (4, 'UnAssignedUser')])),
                ('company_id', models.CharField(blank=True, max_length=36, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by_user_id', models.CharField(default='', max_length=36)),
            ],
            options={
                'db_table': 'invitations',
                'indexes': [models.Index(fields=['email'], name='invitations_email_6e7169_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('quantity_changed', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_histories', to='shop.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_histories', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='shop.product')),
            ],
            options={
                'db_table': 'product_histories',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='shop.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shop.customer')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('buying_price_at_sale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_buying_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_items', to='shop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.sale')),
            ],
            options={
                'db_table': 'sale_items',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_products', models.IntegerField(default=0)),
                ('last_purchase_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suppliers', to='shop.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.supplier'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='companies_owner_i_24e005_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company'], name='categories_company_5233a9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company'], name='customers_company_df4bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='producthistory',
            index=models.Index(fields=['company'], name='product_his_company_06dd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_da_0f99d4_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by'], name='sales_created_6c4eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company'], name='sales_company_549ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'sale_date'], name='sales_company_ca1cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company'], name='suppliers_company_e8beb7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='products_company_7fb65d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='products_company_f3c0b4_idx'),
        ),
    ]
