# Generated by Django 6.0.1 on 2026-02-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_branch_user_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Suspended')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='BranchId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shop.branch'),
        ),
    ]
